### PR TITLE
stable ruby required version

### PR DESCRIPTION
**Pull request by vinagrito**
@nobu 
Would this sound like something reasonable?

### CODE REVIEW

**Comment by hsbt** [comment]
Why do you need fileutils gem on Ruby 2.4.1?

**Comment by vinagrito** [comment]
@hsbt at some point I thought it would be safer to have code running on a stable version. I mean just for the sake of knowing that you're running on a version that has been througly tested. 
Besides, projects run several gems at the time and if I find that the latest `dev` version is not compatible with one of my gems then it might discourage me from using that `dev` version.

Out of curiosity, who do you guys decide which version to require?

**Comment by hsbt** [comment]
>Out of curiosity, who do you guys decide which version to require?

It's me.

fileutils on the standard library of Ruby 2.4.1 is safety version. You don't need to add fileutils gem to your environment. I have no plan to ship fileutils for Ruby 2.4.1 now.

**Comment by vinagrito** [comment]
I respect the plans you might/ might not have for it. I just want to understand why enforcing a non stable ruby version?

**Comment by hsbt** [comment]
> I just want to understand why enforcing a non stable ruby version?

It is still development version yet. After Ruby 2.5.0 release, I will consider unlock for old stable version, maybe.

**Pull request closed without merging**
